on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: |
        export $DOCKERHUB_PASS
        export $AWS_ACCESS_KEY_ID
        export $AWS_SECRET_ACCESS_KEY
        ./deploy.sh
      env:
        DOCKERHUB_PASS: '${{ secrets.DOCKERHUB_PASS }}'
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'

