on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: ./deploy.sh
      env:
        DOCKERHUB_PASS: '${{ secrets.DOCKERHUB_PASS }}'

