on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: |
        export '${{ secrets.DOCKERHUB_PASS }}'
        export '${{ secrets.AWS_ACCESS_KEY_ID }}'
        export '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        ./deploy.sh
